//
//  DetailsPresenter.swift
//  Notes
//
//  Created by Rivi Elf on 01/01/2020.
//  Copyright (c) 2020 Rivi Elf. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic
{
    func configreView(note: Note)
}

class DetailsPresenter: DetailsPresentationLogic
{
    func configreView(note: Note) {
        let vm = DetailViewModel(note: note)
        viewController?.onConfigureView(viewModel: vm)
    }
    
  weak var viewController: DetailsDisplayLogic?
  
  
  
}
