//
//  NotesListTVCPresenter.swift
//  Notes
//
//  Created by Rivi Elf on 28/12/2019.
//  Copyright (c) 2019 Rivi Elf. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotesListTVCPresentationLogic
{
  func displayNextScreen()
  func viewDidLoad(response: ListResponse)
  func reloadTable(response: ListResponse)
}

class NotesListTVCPresenter: NotesListTVCPresentationLogic
{
    
   
    
  weak var viewController: NotesListTVCDisplayLogic?
  
  // MARK: Do something
    
    func viewDidLoad(response: ListResponse) {
        let viewModel = ListViewModel(response: response)
        viewController?.onViewDidLoad(viewModel: viewModel)
    }
    
  
    func displayNextScreen(){
        viewController?.displayNextScreen()
    }
   
    
    func reloadTable(response:ListResponse) {
        let viewModel = ListViewModel(response: response)
        viewController?.reloadTable(viewModel: viewModel)
    }
    
       
  
  
}
