//
//  NotesListResponseModels.swift
//  Notes
//
//  Created by Rivi Elf on 02/01/2020.
//  Copyright (c) 2020 Rivi Elf. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NotesListResponse
{
  // MARK: Use cases
  
  enum NotesListModel
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
