//
//  NotesListTVCRouter.swift
//  Notes
//
//  Created by Rivi Elf on 28/12/2019.
//  Copyright (c) 2019 Rivi Elf. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NotesListTVCRoutingLogic
{
  func routeToShowDetail(segue: UIStoryboardSegue?)
}

protocol NotesListTVCDataPassing
{
  var dataStore: NotesListDataStore? { get }
}

class NotesListTVCRouter: NSObject, NotesListTVCRoutingLogic, NotesListTVCDataPassing
{
    
  weak var viewController: NotesListTVCViewController!
  var dataStore: NotesListDataStore?
  
  // MARK: Routing
    
    func routeToShowDetail(segue: UIStoryboardSegue?) {
         guard let destinationVC =  segue?.destination as? DetailsViewController else {
            return
          }
        if var  destinationDS = destinationVC.router?.dataStore {
             passDataToDetail(source: dataStore!, destination: &destinationDS)
        }
        
    }
    

  // MARK: Passing data
  
  func passDataToDetail(source: NotesListDataStore, destination: inout DetailsDataStore)
  {
    destination.selectedNote = source.selectedNote
    destination.worker = source.worker
  }
}
