//
//  NotesListTVCModels.swift
//  Notes
//
//  Created by Rivi Elf on 28/12/2019.
//  Copyright (c) 2019 Rivi Elf. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Note {
    var id: String
    var type: UseCase
    var title: String? = nil
    var content: String? = nil
}



struct ListResponse {
    var notes: [Note]
    var title: String
    var useCase: UseCase
}

struct ListViewModel {
    private var response: ListResponse
    var title: String
    var useCase: UseCase
    
    init(response: ListResponse) {
        self.response = response
        self.title = response.title
        self.useCase = response.useCase
    }
    
   
   
    var count: Int {
        return response.notes.count
    }
    
    func noteFor(index: IndexPath) -> Note {
        return response.notes[index.row]
    }
    
    func titleForNote(index:IndexPath) -> String {
        let note = response.notes[index.row]
        return note.title ?? ""
    }
}



